# Generated by Django 3.2.9 on 2021-11-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('pc', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=60)),
                ('int_num', models.IntegerField()),
                ('ext_num', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_hour', models.CharField(max_length=80)),
                ('closing_hour', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantData.direction')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantData.restaurant_type')),
            ],
        ),
    ]
